#%RAML 1.0 DataType

type: object
properties:
      orderID:
        description: unique Id corresponds to order
        example: 1
        type: number
        format: int
      placementDate:
        description: Date of order placement
        example: 12/12/12
        type: string
      customerName:
        description: Name of the customer
        example: Varun
        type: string